### ISSUE TITLE
UI 🎉(Admin Dashboard)

### ISSUE THREAD

**Issue by vincentiroleh** [rad5academy/pudio#8]
Admin should be able to:
- Add a podcast title
- Add a podcast author
- Add a podcast file (audio)
- Submit podcast 

**Dev Note**
Create a form with three inputs of the title, author (type text), and file (type file). With the submit button.

**Comment by blexnmirian** [comment]
i want to work on this feature

**Comment by vincentiroleh** [comment]
> i want to work on this feature

That will be nice, you can go ahead and work on it.
